### ISSUE TITLE
Reset implementation in CircuitBreaker

### ISSUE THREAD

**Issue by bagasprstyadi** [eapache/go-resiliency#15]
From what I see in this repository, this circuit breaker does not have a function to reset itself, so that the treshold all resets but without creating new CircuitBreaker. This help so much when the circuit breaker is intended to do multiple breaker on diffrent function in one file.

**Comment by eapache** [comment]
Hi, thanks for the suggestion but I'm not sure I understand the use case. A breaker is only useful when used consistently over a long sequence of calls; if you want to break multiple different functions separately you should use multiple breakers, since resetting the breaker between each call is going to prevent it from ever opening?

It's also worth noting that a reset method isn't trivial to write because it would need to be able to interrupt the `timer` method used for the half-open state when taking the lock, which I don't see an easy way to do.
