### ISSUE TITLE
Retry / Backoff

### ISSUE THREAD

**Issue by eapache** [eapache/go-resiliency#4]
As the title says, it might be handy to have a package for retriable actions with different back-off strategies etc.

**Comment by source-creator** [comment]
Hi, thanks for the cool project.
I have been using retrier with ExponentialBackoff, and have an idea for a feature.

I would like to set a ceiling for ExponentialBackoff, to prevent it from growing too high in case of a failure.  Eg, I should be able to set the ceiling to 24 hours, so that it can continue retrying every day, and not turn from days into weeks...

**Comment by eapache** [comment]
That's a neat idea; the existing backoff methods are pluggable, so you should be able to write that piece locally and still use the rest of the package. I'm happy to take it as a pull request too (probably as a new method, not an addition to the existing `ExponentialBackoff`).
